services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweR123.
      POSTGRES_DB: pvp
    ports:
      - "5432:5432"
    volumes:
      - pvp-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    image: pvp-ratings-service:latest
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    command: >
      sh -lc "npx typeorm migration:run -d ./dist/db-config/data-source.js"

  pvp-ratings-service:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"

volumes:
  pvp-pgdata: